# Generated by Django 2.2.2 on 2019-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deactivation_reason', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, default=None, max_length=16, null=True, unique=True)),
                ('first_name', models.CharField(default=None, max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('username', models.CharField(blank=True, max_length=256, unique=True)),
                ('display_Image', models.FileField(blank=True, upload_to='DisplayImage')),
                ('description', models.TextField(default=None, max_length=200)),
                ('city', models.CharField(default=None, max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
                'db_table': 'db_user_profile_table',
            },
        ),
    ]
